name: example-rest
version: 0.0.0
description: >
  Just an example application to show off dart-rest.
author: Matthew Coleman <matthew@eudaimonia.com>
homepage: https://github.com/spacez320/dart-rest
environment:
  sdk: '>=1.3.0'
dependencies:
  rest: '>0.0.1'
