name: rest
version: 0.1.7-alpha
description: >
  This is a helper for creating RESTful applications. It also comes equipped
  with an implementation for HTTP REST.
author: Matthew Coleman <mcoleman@wayfair.com>
homepage: https://github.com/spacez320/dart-rest
environment:
  sdk: ">=1.3.0"
dependencies:
  unittest: any
