name: rest
version: 0.2.5
description: >
  REST application helper.
author: Matthew Coleman <mcoleman@eudaimonia.com>
homepage: https://github.com/spacez320/dart-rest
environment:
  sdk: '>=1.3.0'
dependencies:
  http: '>=0.11.1 <0.12.0'
dev_dependencies:
  unittest: '>=0.11.5< 0.12.0'
